pms/document/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required

from .views import (
    DocumentDetailView, DocumentCreateView, 
    DocumentUpdateView, DocumentDeleteView, DocumentPrintView, 
    document_copy_view, document_export_view, document_search_view, document_ar_view,
)

urlpatterns = patterns('',
    url(r'^$', login_required(document_search_view), name='document-search'),
    url(r'^add/$', login_required(DocumentCreateView.as_view()), name='document-add'),
    url(r'^export$', login_required(document_export_view), {'export_all': False}, name='document-export'),
    url(r'^export/all$', login_required(document_export_view), {'export_all': True}, name='document-export-all'),
    url(r'^(?P<doc_no>\d+)$', login_required(DocumentDetailView.as_view()), name='document-detail'),
    url(r'^(?P<doc_no>\d+)/edit$', login_required(DocumentUpdateView.as_view()), name='document-edit'),
    url(r'^(?P<doc_no>\d+)/copy$', login_required(document_copy_view), name='document-copy'),
    url(r'^(?P<doc_no>\d+)/delete$', login_required(DocumentDeleteView.as_view()), name='document-delete'),
    url(r'^(?P<doc_no>\d+)/print$', login_required(DocumentPrintView.as_view()), name='document-print'),
    url(r'^report/ar$', login_required(document_ar_view), name='document-report-ar'),
)

pms/pms/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

from pms.version import VERSION
from utils import database

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'extra_context': {'version':VERSION}}, name='login'),
    url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'next_page':'dashboard'}, name='logout'),

    url(r'^$', 'dash.views.dashboard', name='dashboard'),
    url(r'^about$', 'dash.views.about', name='about'),

    url(r'^client/', include('client.urls')),
    url(r'^document/', include('document.urls')),
    url(r'^db/download', database.download, name='db_download'),
)

pms/client/models.py
import logging

from django.db import models
from django.core.urlresolvers import reverse_lazy

from pms import settings

class Client(models.Model):
    STATUS_TYPE = (
        ('A', 'Active'),
        ('I', 'Inactive'),
    )
    company = models.CharField(unique=True, max_length=64)
    address1 = models.CharField(blank=True, max_length=64)
    address2 = models.CharField(blank=True, max_length=64)
    city = models.CharField(blank=True, max_length=64)
    prov = models.CharField(blank=True, max_length=64)
    postcode = models.CharField(blank=True, max_length=12)
    country = models.CharField(blank=True, max_length=32)
    status = models.CharField(max_length=1, choices=STATUS_TYPE, default='A')
    first_txn_date = models.DateField(null=True, blank=True)
    last_txn_date = models.DateField(null=True, blank=True)
    remark = models.TextField(blank=True, default='')

    class Meta:
        ordering = ["company"]

    def __str__(self):
        return self.company

    def get_absolute_url(self):
        return reverse_lazy('client-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        self.company = self.company.strip()
        self.address1 = self.address1.strip()
        self.address2 = self.address2.strip()
        self.city = self.city.strip()
        self.prov = self.prov.strip()
        self.postcode = self.postcode.strip()
        self.country = self.country.strip()
        super().save(*args, **kwargs)

def client_export(writer):
    """
    writer is a csv writer object to export data to.
    """
    logger = logging.getLogger(settings.U_LOGGER_ROOT + __name__)
    logger.info('client exported')
    writer.writerow([
        "Company",
        "Address1",
        "Address2",
        "City",
        "Prov",
        "Postcode",
        "Country",
        "Status",
        "first_txn_date",
        "Last_txn_date",
        "Remark",
    ])
    for client in Client.objects.order_by('company'):
        writer.writerow([
            client.company,
            client.address1,
            client.address2,
            client.city,
            client.prov,
            client.postcode,
            client.country,
            client.status,
            client.first_txn_date,
            client.last_txn_date,
            client.remark,
        ])

pms/document/forms.py
import datetime

from django import db
from django import forms

from .models import Document, DocumentLine
from client.models import Client

def make_custom_datefield(f, **kwargs):
    formfield = f.formfield(**kwargs)
    if isinstance(f, db.models.DateField):
        formfield.widget.attrs.update({'class':'datePicker'})
    return formfield

class DocumentForm(forms.ModelForm):
    formfield_callback = make_custom_datefield
    class Meta:
        model = Document
        fields = [
            'client', 
            'doc_type', 
            'doc_date', 
            'doc_note', 
            'gst_apply', 
            'pst_apply', 
            'remark', 
            'paid_date',
            'paid_ref', 
            'status', 
            ]
        widgets = {
            'doc_note': forms.Textarea(attrs={'rows':4}),
            'remark': forms.Textarea(attrs={'rows':4}),
            }

LineFormSet = forms.models.inlineformset_factory(Document, DocumentLine, 
                  fields=['seqno', 'sku', 'desc', 'qty', 'unit_price'], 
                  widgets={
                    'seqno': forms.TextInput(attrs={'size':'10'}),
                    'sku': forms.TextInput(attrs={'size':'10'}),
                    'desc': forms.TextInput(attrs={'size':'50'}),
                    'qty': forms.TextInput(attrs={'size':'10'}),
                    'unit_price': forms.TextInput(attrs={'size':'10'})},
                  extra=2)

class SearchForm(forms.Form):
    client = forms.ModelChoiceField(
                required=False, 
                queryset = Client.objects.all(),
                )
    date_from = forms.DateField(
                required=False, 
                label="Date From", 
                initial=datetime.date(datetime.date.today().year,1,1), 
                widget=forms.TextInput(attrs={'class':'datePicker'}),
                )
    date_to = forms.DateField(
                required=False, 
                label="Date To", 
                initial=datetime.date.today, 
                widget=forms.TextInput(attrs={'class':'datePicker'}),
                )
    paid = forms.ChoiceField(
                required=False, 
                label="Paid", 
                choices=(('',''), ('y','Yes'),('n','No')),
                )

pms/document/views.py
import datetime
import pickle

from django.contrib.auth.decorators import permission_required
from django.core.urlresolvers import reverse_lazy
from django.db.models import Count, Sum
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView, View

from pms.settings import U_FORCE_ATTACHMENT
from report.documentreport import DocumentReport
from .models import Document, DocumentLine, document_export
from .forms import DocumentForm, LineFormSet, SearchForm

class DocumentDetailView(DetailView):
    model = Document
    template_name = 'document/detail.html'
    slug_field = 'doc_no'
    slug_url_kwarg = 'doc_no'

    def get_context_data(self, **kwargs):
        context = super(DocumentDetailView, self).get_context_data(**kwargs)
        doc = get_object_or_404(Document, doc_no=self.kwargs['doc_no'])
        context['lines'] = DocumentLine.objects.filter(document=doc)
        return context

class DocumentCreateView(CreateView):
    model = Document
    template_name = 'document/edit.html'
    slug_field = 'doc_no'
    slug_url_kwarg = 'doc_no'
    form_class = DocumentForm

    def get_success_url(self):
        return reverse_lazy('document-detail', args=(self.object.doc_no,))

    def form_valid(self, form):
        context = self.get_context_data()
        line_formset = context['line_formset']
        if line_formset.is_valid():
            # Save and commit the doc to get the doc id for saving the lines
            # and then save the doc again to update the subtotals. 
            self.object = form.save()
            line_formset.instance = self.object
            line_formset.save()
            form.save()
            # re-assign line seqnos
            if line_formset.has_changed():
                seqno = 10
                doc = Document.objects.get(doc_no=self.object.doc_no)
                for line in doc.documentline_set.order_by('seqno'):
                    line.seqno = seqno
                    line.save()
                    seqno += 10
            return super(DocumentCreateView, self).form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(DocumentCreateView, self).get_context_data(**kwargs)
        if self.request.method == 'POST':
            context['line_formset'] = LineFormSet(self.request.POST)
        elif self.request.method == 'GET':
            context['line_formset'] = LineFormSet()
        return context
           
class DocumentUpdateView(UpdateView):
    model = Document
    template_name = 'document/edit.html'
    slug_field = 'doc_no'
    slug_url_kwarg = 'doc_no'
    form_class = DocumentForm

    def get_success_url(self):
        return reverse_lazy('document-detail', args=(self.object.doc_no,))

    def form_valid(self, form):
        context = self.get_context_data()
        line_formset = context['line_formset']
        if line_formset.is_valid():
            # Save the doc to get the doc object for saving the lines
            # and then save the doc again to update the subtotals.
            # There is no need to commit the first time the doc is saved
            # because we don't need to generate a new doc id in update mode.
            self.object = form.save(commit=False)
            line_formset.instance = self.object
            line_formset.save()
            form.save()
            # re-assign line seqnos
            if line_formset.has_changed():
                seqno = 10
                doc = Document.objects.get(doc_no=self.object.doc_no)
                for line in doc.documentline_set.order_by('seqno'):
                    line.seqno = seqno
                    line.save()
                    seqno += 10
            return super(DocumentUpdateView, self).form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))

    def form_invalid(self, form):
        return self.render_to_response(self.get_context_data(form=form))

    def get_context_data(self, **kwargs):
        context = super(DocumentUpdateView, self).get_context_data(**kwargs)
        if self.request.method == 'POST':
            context['line_formset'] = LineFormSet(self.request.POST, instance=self.object)
        elif self.request.method == 'GET':
            context['line_formset'] = LineFormSet(instance=self.object)
        return context
           
class DocumentDeleteView(DeleteView):
    template_name = 'document/delete.html'
    model = Document
    slug_field = 'doc_no'
    slug_url_kwarg = 'doc_no'
    success_url = reverse_lazy('document-search')

class DocumentPrintView(View):
    def get(self, request, doc_no):
        doc = get_object_or_404(Document, doc_no=doc_no)
        report = DocumentReport()
        pdf = report.run(doc=doc)
        response = HttpResponse(content_type='application/pdf')
        filename = "%s.pdf" % report.title
        if U_FORCE_ATTACHMENT:
            response['Content-Disposition'] = 'attachment; filename="%s"' % filename
        else:
            response['Content-Disposition'] = 'filename="%s"' % filename
        response.write(pdf)
        return response

@permission_required('permission.export')
def document_export_view(request, export_all):
    EXPORT_FILE = 'documents.csv'
    import csv
    from pms.settings import U_FORCE_ATTACHMENT

    if export_all:
        docs = Document.objects.order_by('doc_no')
    else:
        saved_query = request.session.get('document_search_query')
        if saved_query:
            query = pickle.loads(saved_query)
            docs = Document.objects.all()
            docs.query = query
        else:
            docs = None

    response = HttpResponse(content_type='text/csv')
    if U_FORCE_ATTACHMENT:
        response['Content-Disposition'] = 'attachment; filename="%s"' % EXPORT_FILE
    else:
        response['Content-Disposition'] = 'filename="%s"' % EXPORT_FILE
    writer = csv.writer(response)
    document_export(writer, docs)
    return response

def document_search_view(request):
    template_name = "document/search.html"
    object_list = None
    count = 0
    subtotal = 0 # before taxes
    grand_total = 0 # after taxes

    if request.method == 'POST':
        form = SearchForm(request.POST)
    else:
        data = {
            'date_from': datetime.date(datetime.date.today().year, 1, 1),
            'date_to': datetime.date.today(),
        }
        form = SearchForm(data)

    if form.is_valid():

        # retrieve documents based on selection criteria
        # and pickle the query in the session for export use
        client = form.cleaned_data['client']
        date_from = form.cleaned_data['date_from']
        date_to = form.cleaned_data['date_to']
        paid = form.cleaned_data['paid']
        kw = {}
        if client: kw['client'] = client
        if date_from: kw['doc_date__gte'] = date_from
        if date_to: kw['doc_date__lte'] = date_to
        #import pdb; pdb.set_trace()
        if paid == 'y':
            kw['paid_date__isnull'] = False
        elif paid == 'n':
            kw['paid_date__isnull'] = True
        object_list = Document.objects.filter(**kw)
        if object_list:
            request.session['document_search_query'] = pickle.dumps(Document.objects.filter(**kw).query)
        else:
            request.session['document_search_query'] = None

        # calculate the summary information 
        result = Document.objects.filter(**kw).aggregate(
            count=Count('id'),
            subtotal=Sum('subtotal'),
            grand_total=Sum('total'),
            )
        count = result['count']
        subtotal = result['subtotal']
        grand_total = result['grand_total']

    return render(request, template_name, 
        { 'form': form, 'object_list':object_list,
          'count':count, 'subtotal':subtotal, 'grand_total':grand_total,})

def document_copy_view(request, doc_no):
    template_name = "document/copy.html"

    if request.method == 'POST':
        doc1 = get_object_or_404(Document, doc_no=doc_no) 
        doc2 = doc1.copy()
        response = redirect('document-detail', doc2.doc_no)
    elif request.method == 'GET':
        object = get_object_or_404(Document, doc_no=doc_no) 
        response = render(request, template_name, {'object': object,})
    else:
        response = redirect('document-search')
    return response

def document_ar_view(request):
    template_name = "document/ar.html"
    object_list = None
    count = 0
    grand_total = 0

    # retrieve outstanding invoices
    kw = {'paid_date': None, 'doc_type': 'I'}
    object_list = Document.objects.filter(**kw)

    # calculate the summary information 
    result = Document.objects.filter(**kw).aggregate(
        count=Count('id'), grand_total=Sum('total'))
    count = result['count']
    grand_total = result['grand_total']

    return render(request, template_name, 
        { 'object_list':object_list,
          'count':count, 'grand_total':grand_total,})

pms/document/templates/document/ar.html
{% extends "base.html" %}
{% load staticfiles %}
{% load l10n %}

{% block css %}
    <link href="{% static "jquery-ui/css/jquery-ui.min.css" %}" rel="stylesheet">
    {% endblock %}

{% block script %}
    <script src="{% static "jquery-ui/js/jquery-ui.min.js" %}"></script>
    <script>
    // on page load
    $(document).ready(
      function(){
        $( ".datePicker" ).datepicker( {dateFormat: 'yy-mm-dd'} );
      }
    );
    </script>
    {% endblock %}

{% block content %}

<h3>A/R Report</h3>

<div>

{% if object_list %}
<br>
Count = {{ count }} Grand Total = $ {{ grand_total }}
<table class="table table-striped table-bordered">
  <tr>
    <th>Doc #</th>
    <th>Client</th>
    <th>Date</th>
    <th>Total</th>
  </tr>
  {% for doc in object_list %}
  <tr>
    <td><a href="{% url "document-detail" doc.doc_no %}">{{ doc.doc_no|unlocalize }}</a></td>
    <td>{{ doc.client }}</td>
    <td>{{ doc.doc_date|date:"Y-m-d" }}</td>
    <td style="text-align: right">$ {{ doc.total|floatformat:"2"}}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
  No outstanding invoice.
{% endif %}

{% endblock %}

pms/document/templates/document/copy.html
{% extends "base.html" %}

{% block content %}

<h3>Copy Document</h3>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to copy "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

pms/document/templates/document/delete.html
{% extends "base.html" %}

{% block content %}

<h3>Delete Document</h3>
<form action="" method="post">{% csrf_token %}
    <p>Are you sure you want to delete "{{ object }}"?</p>
    <input type="submit" value="Confirm" />
</form>

{% endblock %}

pms/document/templates/document/detail.html
{% extends "base.html" %}
{% load l10n %}

{% block content %}

<h3>Document #{{ object.doc_no|unlocalize }}</h3>

<div class="row">
  <div class="col-md-6">
    <table width="100%" class="table-condensed">
      <tr><td width="20%" class="caption">Client:</td><td width="80%">{{ object.client }}</td></tr>
      <tr><td class="caption">Doc Type:</td><td>{{ object.get_doc_type_display }}</td></tr>
      <tr><td class="caption">Doc Date:</td><td>{{ object.doc_date|date:"Y-m-d" }}</td></tr>
      <tr><td class="caption">Subtotal:</td><td>{{ object.subtotal|floatformat:"2" }}</td></tr>
      <tr><td class="caption">GST:</td><td>{{ object.gst|floatformat:"2" }}</td></tr>
      <tr><td class="caption">PST:</td><td>{{ object.pst|floatformat:"2" }}</td></tr>
      <tr><td class="caption">Total:</td><td>{{ object.total|floatformat:"2" }}</td></tr>
      <tr><td class="caption">Paid Date:</td><td>{{ object.paid_date|date:"Y-m-d" }}</td></tr>
      <tr><td class="caption">Paid Ref:</td><td>{{ object.paid_ref }}</td></tr>
      <tr><td class="caption">Status:</td><td>{{ object.get_status_display }}</td></tr>
    </table>
  </div>
  <div class="col-md-6">
    <table width="100%" class="table-condensed">
      <tr><td width="20%" class="caption">Doc Note:</td><td width="80%">{{ object.doc_note }}</td></tr>
      <tr><td class="caption">Remark:</td><td>{{ object.remark }}</td></tr>
    </table>
  </div>
</div>

<table class="table">
  <tr>
    <th>Seqno</th>
    <th>SKU</th>
    <th>Desc</th>
    <th style="text-align: right">Qty</th>
    <th style="text-align: right">Unit Price</th>
    <th style="text-align: right">Total</th>
  </tr>
  {% for line in lines %}
  <tr>
    <td>{{ line.seqno }}</td>
    <td>{{ line.sku }}</td>
    <td>{{ line.desc }}</td>
    <td style="text-align: right">{{ line.qty|floatformat:"2" }}</td>
    <td style="text-align: right">{{ line.unit_price|floatformat:"2" }}</td>
    <td style="text-align: right">{{ line.total|floatformat:"2" }}</td>
  </tr>
{% endfor %}
</table>
Total lines = {{ object.documentline_set.all|length }}<br/>

<br/>
<a href="{% url "document-search" %}">List</a> | 
<a href="{% url "document-edit" object.doc_no %}">Edit</a> | 
<a href="{% url "document-add" %}">New</a> | 
<a href="{% url "document-copy" object.doc_no %}">Copy</a> | 
<a href="{% url "document-print" object.doc_no %}">Print</a> | 
<a href="{% url "document-delete" object.doc_no %}">Delete</a>

{% endblock %}

pms/document/templates/document/edit.html
{% extends "base.html" %}
{% load staticfiles %}
{% load l10n %}

{% block css %}
    <link href="{% static "jquery-ui/css/jquery-ui.min.css" %}" rel="stylesheet">
    {% endblock %}

{% block script %}
    <script src="{% static "jquery-ui/js/jquery-ui.min.js" %}"></script>
    <script>
    // on page load
    $(document).ready(
      function(){
        $( ".datePicker" ).datepicker( {dateFormat: 'yy-mm-dd'} );
      }
    );
    </script>
    {% endblock %}

{% block content %}

    {% if object.doc_no %}
        <h3>Document #{{ object.doc_no|unlocalize }}</h3>
    {% else %}
        <h3>Add New Document</h3>
    {% endif %}

    <form action="" method="post">
        
        {{ form.errors }}
        <div class="row">
          <div class="col-md-6">
            <table width="100%" class="table-condensed">
              <tr><td class="caption" width="20%">{{ form.client.errors }}{{ form.client.label_tag }}</td><td width="80%">{{ form.client }}</td></tr>
              <tr><td class="caption">{{ form.doc_type.label_tag }} </td><td> {{ form.doc_type.errors }}  {{ form.doc_type }}</td></tr>
              <tr><td class="caption">{{ form.doc_date.label_tag }} </td><td> {{ form.doc_date.errors }}  {{ form.doc_date }}</td></tr>
              <tr><td class="caption">{{ form.gst_apply.label_tag }}</td><td> {{ form.gst_apply.errors }} {{ form.gst_apply }}</td></tr>
              <tr><td class="caption">{{ form.pst_apply.label_tag }}</td><td> {{ form.pst_apply.errors }} {{ form.pst_apply }}</td></tr>
              <tr><td class="caption">{{ form.paid_date.label_tag }} </td><td> {{ form.paid_date.errors }}  {{ form.paid_date }}</td></tr>
              <tr><td class="caption">{{ form.paid_ref.label_tag }} </td><td> {{ form.paid_ref.errors }}  {{ form.paid_ref }}</td></tr>
              <tr><td class="caption">{{ form.status.label_tag }}   </td><td> {{ form.status.errors }}    {{ form.status }}</td></tr>
            </table>
          </div>
          <div class="col-md-6">
            <table width="100%" class="table-condensed">
              <tr><td width="20%" class="caption">{{ form.doc_note.label_tag }}</td><td width="80%">{{ form.doc_note.errors }}{{ form.doc_note }}</td></tr>
              <tr><td class="caption">{{ form.remark.label_tag }}</td><td>{{ form.remark.errors }}{{ form.remark }}</td></tr>
            </table>
          </div>
        </div>

        {{ line_formset.management_form }}
        {{ line_formset.non_form_errors }}
        <table>
        {% for form in line_formset.forms %}
          {% if forloop.first %}
            <tr>
              {% for field in form.visible_fields %}
              <th>{{ field.label|capfirst }}</th>
              {% endfor %}
            </tr>
          {% endif %}
          <tr>
          {% for field in form.visible_fields %}
            {% if forloop.first %}
              {% for hidden in form.hidden_fields %}
              {{ hidden }}
              {% endfor %}
            {% endif %}
            <td>
              {{ field.errors.as_ul }}
              {{ field }}
            </td>
          {% endfor %}
          </tr>
        {% endfor %}
        </table>

        {% csrf_token %}
        <input type="submit" value="Save" />

    </form>

    {% endblock %}

pms/document/templates/document/search.html
{% extends "base.html" %}
{% load staticfiles %}
{% load l10n %}

{% block css %}
    <link href="{% static "jquery-ui/css/jquery-ui.min.css" %}" rel="stylesheet">
    {% endblock %}

{% block script %}
    <script src="{% static "jquery-ui/js/jquery-ui.min.js" %}"></script>
    <script>
    // on page load
    $(document).ready(
      function(){
        $( ".datePicker" ).datepicker( {dateFormat: 'yy-mm-dd'} );
      }
    );
    </script>
    {% endblock %}

{% block content %}

<h3>Document Search</h3>

<div>
<form action="" method="post">
  {% csrf_token %}
  {{ form.non_field_errors }}
  <table>
    <tr><td>{{ form.client.label_tag }}</td><td>{{ form.client }}</td><td>{{ form.client.errors }}</td></tr>
    <tr><td>{{ form.date_from.label_tag }}</td><td>{{ form.date_from }}</td><td>{{ form.date_from.errors }}</td></tr>
    <tr><td>{{ form.date_to.label_tag }}</td><td>{{ form.date_to }}</td><td>{{ form.date_to.errors }}</td></tr>
    <tr><td>{{ form.paid.label_tag }}</td><td>{{ form.paid }}</td><td>{{ form.paid.errors }}</td></tr>
    <tr><td colspan="2">
      <input type="submit" value="Search" />
      <input type="button" onclick="window.location=''" value="Reset"/>
      <input type="button" onclick="window.location='{% url "document-add" %}'" value="New" />
      <input type="button" onclick="window.location='{% url "document-export" %}'" value="Export" />
    </td></tr>
  </table>
</form>
</div>

{% if object_list %}
<br>
Count = {{ count }} | Subtotal = $ {{ subtotal }} | Grand Total = $ {{ grand_total }}
<table class="table table-striped table-bordered">
  <tr>
    <th>Doc #</th>
    <th>Client</th>
    <th>Date</th>
    <th style="text-align: right">Subtotal</th>
    <th style="text-align: right">Total</th>
  </tr>
  {% for doc in object_list %}
  <tr>
    <td><a href="{% url "document-detail" doc.doc_no %}">{{ doc.doc_no|unlocalize }}</a></td>
    <td>{{ doc.client }}</td>
    <td>{{ doc.doc_date|date:"Y-m-d" }}</td>
    <td style="text-align: right">$ {{ doc.subtotal|floatformat:"2"}}</td>
    <td style="text-align: right">$ {{ doc.total|floatformat:"2"}}</td>
  </tr>
  {% endfor %}
</table>
{% else %}
  No document found.
{% endif %}

{% endblock %}